require "locaweb-emailmarketing/client"
require "locaweb-emailmarketing/clients/base_client"
require 'locaweb-emailmarketing/clients/account_client'
require 'locaweb-emailmarketing/clients/campaign_client'
require 'locaweb-emailmarketing/clients/contact_client'
require 'locaweb-emailmarketing/clients/contact_import_client'
require 'locaweb-emailmarketing/clients/custom_field_client'
require 'locaweb-emailmarketing/clients/domain_client'
require 'locaweb-emailmarketing/clients/list_client'
require 'locaweb-emailmarketing/clients/message_client'
require 'locaweb-emailmarketing/clients/report_client'